#端口配置
server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  #Redis配置
  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: 47.101.54.228
#    host: 127.0.0.1
    port: 6379
    password:  #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间（毫秒）
  servlet:
    multipart:
      enabled: true  #是否开启文件上传支持
      max-file-size: 30MB  #上传单个文件的最大大小，默认为1MB
      max-request-size: 100MB  #上传多文件时文件的总大小，默认为10MB
  main:
    allow-bean-definition-overriding: true

#自定义文件上传路径
image:
  upload:
    windowsPath: E:/IdeaProjects/campusblog/upload/images/
    linuxPath: /usr/images/

#MyBatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启MyBatis驼峰命名规则自动转换

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true #为true时，当前页大于总页数时，会返回最后一页，为false时，有数据就返回，没数据则为空
  support-methods-arguments: true
  params: countSql

#日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    com.zs.campusblog.dao: DEBUG

# 自定义jwt key
jwt:
  tokenHead: Bearer  #JWT负载中拿到开头
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4Fc597NmEGWtT4XvRgjU # 访问身份验证中用到用户标识
    accessKeySecret: zfB5j3VbbLd4NdoS9u4gs3eeXn5pAE # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: campusblog # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://campusblog.qicp.vip/ # 文件上传成功后的回调地址
    dir:
      prefix: images/ # 上传文件夹路径前缀

minio:
  endpoint: http://47.101.54.228:9090 # MinIO服务所在地址
  bucketName: campusblog # 存储桶名称
  accessKey: minioadmin # 访问的key
  secretKey: minioadmin # 访问的秘钥

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /images/**
      - /druid/**
      - /user/login
      - /user/register
      - /user/info
      - /user/logout
      - /minio/upload
      - /api/**
      - /index.html
      - /static/**